"""Numeric oracles for live federation cross-engine slots."""

from __future__ import annotations

from decimal import Decimal

# Sandbox subset corpus (partition seeds on storefront + catalog before full rebuild)
SANDBOX_SUBSET_JOIN_RENTAL_LINKED_TITLES = 192
SANDBOX_SUBSET_PAYMENT_TOTAL = Decimal("6947.73")
SANDBOX_SUBSET_HORROR_DISTINCT_CUSTOMERS = 22
SANDBOX_SUBSET_HORROR_PARTIAL_SUM_WRONG = 27

# Full live partition load across storefront, catalog, logistics and crm
LIVE_FULL_JOIN_RENTAL_LINKED_TITLES = 18758
LIVE_FULL_PAYMENT_TOTAL = Decimal("58596.41")
LIVE_FULL_HORROR_DISTINCT_CUSTOMERS = 555

# Backward-compatible aliases for sandbox-subset callers
JOIN_RENTAL_LINKED_TITLES = SANDBOX_SUBSET_JOIN_RENTAL_LINKED_TITLES
PAYMENT_TOTAL = SANDBOX_SUBSET_PAYMENT_TOTAL
HORROR_DISTINCT_CUSTOMERS = SANDBOX_SUBSET_HORROR_DISTINCT_CUSTOMERS
HORROR_PARTIAL_SUM_WRONG = SANDBOX_SUBSET_HORROR_PARTIAL_SUM_WRONG

# Single-member questions through the federated engine on the sandbox subset
ACTOR_COUNT = 6
CUSTOMER_COUNT = 73
RENTAL_COUNT = 2262
INVENTORY_COUNT = 542
FILM_CATALOG_ROW_COUNT = 96
CATEGORY_COUNT = 28

# Cross-source logistics delivery rows with a matching storefront rental (orphans excluded)
DELIVERY_RENTAL_LINKED_COUNT = 1

# Full rental_shop PostgreSQL corpus (scripts/source_rental_shop.py targets)
RENTAL_SHOP_FILM_COUNT = 1000
RENTAL_SHOP_ACTOR_COUNT = 200
RENTAL_SHOP_CUSTOMER_COUNT = 599
RENTAL_SHOP_RENTAL_COUNT = 17516
RENTAL_SHOP_STORE_COUNT = 12
RENTAL_SHOP_CATEGORY_COUNT = 28
RENTAL_SHOP_FILM_CATEGORY_COUNT = 16
RENTAL_SHOP_LANGUAGE_COUNT = 6
RENTAL_SHOP_WAREHOUSE_COUNT = 6
RENTAL_SHOP_DELIVERY_STATUS_COUNT = 4
RENTAL_SHOP_PROMOTION_COUNT = 25
RENTAL_SHOP_FILM_RATING_COUNT = 5
RENTAL_SHOP_GAME_PLATFORM_COUNT = 5
