"""Stable import surface for the AetherEngine package."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version
from typing import Any

from ._config import EngineLimits, FederationLimits
from ._contracts_base import (
    AccessError,
    AetherError,
    AetherSpace,
    AggregateJoinFanOutError,
    AmbiguousDateLiteralError,
    ArtifactLockTimeoutError,
    AuditEvent,
    BusinessKnowledgeEntry,
    ClauseWidenedRowsetError,
    ComparisonJoinScopeExceededError,
    ConfigError,
    ConfigSnapshot,
    DatabaseConnectionError,
    DatabaseExecutionError,
    DatabasePingFailed,
    DataQualityReport,
    Diagnostic,
    EngineContext,
    FederationCapExceededError,
    FederationConfigError,
    FederationContext,
    FederationDeclarationError,
    FederationIneligibleError,
    FederationInvariantError,
    FederationJoinFanOutError,
    FederationMalformedMemberAnswerError,
    FederationMappingsAppliedSidecarError,
    FederationMemberExecutionError,
    FederationMemberProbeError,
    FederationMemberUnprofilableError,
    FederationPartialFailureError,
    FederationRuntimeError,
    FederationTurnCancelledError,
    JoinCandidateCapExceededError,
    JoinColumnCountMismatchError,
    JoinInjectionAlignmentError,
    JoinInjectionFailedError,
    JoinPathKeyTypeError,
    JoinPathTieCapExceededError,
    JoinProbeEdgeKindMismatchError,
    LlmJsonExhausted,
    LlmTransientFailure,
    MigrationPendingError,
    MigrationPreview,
    MockFixtureMissingError,
    NoJoinPathError,
    NullInNegatedListError,
    OwnerOnlyOperationError,
    PersistedFederationInspection,
    PhaseProgressEvent,
    PipelineSuspended,
    PlanPreviewResult,
    ProbeCtePlacementError,
    QSimSummarySnapshot,
    RegistryRenderError,
    ResultCapExceededError,
    RetryableDatabaseExecutionError,
    RetryableError,
    RetryableFederationPartialFailureError,
    SchemaAccessError,
    SchemaInvariantError,
    SchemaStatsSnapshot,
    SeedWarmupSummarySnapshot,
    SessionActiveError,
    SessionStep,
    SessionTurnCancelledError,
    SpaceContext,
    StatementTimeoutError,
    SubdayDateWindowOnDateColumnError,
    SuspendedSessionExpiredError,
    TablePreviewResult,
)
from ._contracts_schema import UploadIngestResult
from ._data_quality import inspect_tabular_upload

try:
    __version__ = version("aetherdialect")

except PackageNotFoundError:
    __version__ = "0.0.0+dev"


__all__ = [
    "AccessError",
    "AggregateJoinFanOutError",
    "AetherEngine",
    "AetherError",
    "AetherFederation",
    "AetherSpace",
    "AmbiguousDateLiteralError",
    "ArtifactLockTimeoutError",
    "AsyncPipelineSession",
    "AuditEvent",
    "BusinessKnowledgeEntry",
    "ClauseWidenedRowsetError",
    "ComparisonJoinScopeExceededError",
    "ConfigError",
    "ConfigSnapshot",
    "DatabaseConnectionError",
    "DatabaseExecutionError",
    "DatabasePingFailed",
    "DataQualityReport",
    "Diagnostic",
    "EngineContext",
    "EngineLimits",
    "FederationCapExceededError",
    "FederationConfigError",
    "FederationContext",
    "FederationDeclarationError",
    "FederationIneligibleError",
    "FederationInvariantError",
    "FederationJoinFanOutError",
    "FederationMalformedMemberAnswerError",
    "FederationMappingsAppliedSidecarError",
    "FederationMemberExecutionError",
    "FederationMemberProbeError",
    "FederationMemberUnprofilableError",
    "FederationPartialFailureError",
    "FederationRuntimeError",
    "FederationTurnCancelledError",
    "FederationLimits",
    "JoinCandidateCapExceededError",
    "JoinColumnCountMismatchError",
    "JoinInjectionAlignmentError",
    "JoinInjectionFailedError",
    "JoinPathKeyTypeError",
    "JoinPathTieCapExceededError",
    "JoinProbeEdgeKindMismatchError",
    "LlmJsonExhausted",
    "LlmTransientFailure",
    "MigrationPendingError",
    "MigrationPreview",
    "MockFixtureMissingError",
    "NoJoinPathError",
    "NullInNegatedListError",
    "OwnerOnlyOperationError",
    "PersistedFederationInspection",
    "PhaseProgressEvent",
    "PipelineSession",
    "PipelineSuspended",
    "PlanPreviewResult",
    "ProbeCtePlacementError",
    "QSimSummarySnapshot",
    "ResultCapExceededError",
    "RetryableDatabaseExecutionError",
    "RetryableError",
    "RetryableFederationPartialFailureError",
    "RegistryRenderError",
    "Sandbox",
    "SchemaAccessError",
    "SchemaInvariantError",
    "SchemaStatsSnapshot",
    "SeedWarmupSummarySnapshot",
    "SessionActiveError",
    "SessionStep",
    "SessionTurnCancelledError",
    "SpaceContext",
    "StatementTimeoutError",
    "SubdayDateWindowOnDateColumnError",
    "SuspendedSessionExpiredError",
    "TablePreviewResult",
    "UploadIngestResult",
    "inspect_tabular_upload",
    "__version__",
]


def __getattr__(name: str) -> Any:

    if name in (
        "AetherEngine",
        "AetherFederation",
        "AsyncPipelineSession",
        "PipelineSession",
        "Sandbox",
    ):
        import importlib

        return getattr(importlib.import_module("aetherdialect.aetherdialect"), name)

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:

    return sorted(set(__all__))
